version: '3.3'
services:

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: 'prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway:v1.11.1
    container_name: 'pushgateway'
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:12.3.0-17900959199-ubuntu
    container_name: 'grafana'
    ports:
      - '3000:3000'
