{
 "title": "Spring Batch Prometheus",
 "description": "Dashboard for Spring Batch applications instrumented with Micrometer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Spring Batch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "spring_batch_job_seconds_max", "legendFormat": "{{name}} {{status}}" }
   ]
  },
  {
   "title": "Job execution rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_count[1m]) * 60",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job failure rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(spring_batch_job_seconds_count{status=\"FAILED\"}[5m])) by (name, status)) / (sum(rate(spring_batch_job_seconds_count[5m])) by (name, status))",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Item read throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_item_read_seconds_count[1m])",
     "legendFormat": "read {{status}}"
    }
   ]
  },
  {
   "title": "Item write throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_chunk_write_seconds_count[1m])",
     "legendFormat": "write {{status}}"
    }
   ]
  }
 ]
}