ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ALTER COLUMN SERIALIZED_CONTEXT VARCHAR(MAX) NULL;
ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ALTER COLUMN SERIALIZED_CONTEXT VARCHAR(MAX) NULL;

ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN START_TIME DATETIME NULL;

-- Note: DATE_VAL cannot be dropped in a single statement as it has a DEFAULT NULL constraint
-- and there are several ways of dropping it depending on the version of SQLServer.
-- Dropping DATE_VAL is omitted from this script and left to the user.
-- ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DATE_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN LONG_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DOUBLE_VAL;

EXEC SP_RENAME 'BATCH_JOB_EXECUTION_PARAMS.TYPE_CD', 'PARAMETER_TYPE', 'COLUMN';
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_TYPE VARCHAR(100);

EXEC SP_RENAME 'BATCH_JOB_EXECUTION_PARAMS.KEY_NAME', 'PARAMETER_NAME', 'COLUMN';
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_NAME VARCHAR(100);

EXEC SP_RENAME 'BATCH_JOB_EXECUTION_PARAMS.STRING_VAL', 'PARAMETER_VALUE', 'COLUMN';
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_VALUE VARCHAR(2500);