ALTER TABLE BATCH_JOB_EXECUTION DROP COLUMN JOB_CONFIGURATION_LOCATION;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN PARAMETER_NAME VARCHAR(100) NOT NULL,
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN PARAMETER_TYPE VARCHAR(100) NOT NULL,
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN PARAMETER_VALUE VARCHAR(2500);

-- Ignore UPDATE without WHERE updating all the table on purpose, keeping history.
UPDATE BATCH_JOB_EXECUTION_PARAMS SET PARAMETER_NAME = KEY_NAME WHERE TRUE;  -- NOSONAR
UPDATE BATCH_JOB_EXECUTION_PARAMS
SET PARAMETER_TYPE = CASE
                         WHEN TYPE_CD = 'DATE' THEN 'java.util.Date'
                         WHEN TYPE_CD = 'LONG' THEN 'java.lang.Long'
                         WHEN TYPE_CD = 'DOUBLE' THEN 'java.lang.Double'
                         WHEN TYPE_CD = 'STRING' THEN 'java.lang.String'
                         ELSE 'Error - unsupported TYPE_CD'
                    END
WHERE TRUE; -- NOSONAR
UPDATE BATCH_JOB_EXECUTION_PARAMS
SET PARAMETER_VALUE = CASE
                         WHEN TYPE_CD = 'DATE' THEN DATE_VAL
                         WHEN TYPE_CD = 'LONG' THEN LONG_VAL
                         WHEN TYPE_CD = 'DOUBLE' THEN DOUBLE_VAL
                         WHEN TYPE_CD = 'STRING' THEN STRING_VAL
                         ELSE 'Error - unsupported TYPE_CD'
                    END
WHERE TRUE; -- NOSONAR

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DATE_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN LONG_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN DOUBLE_VAL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN TYPE_CD;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN KEY_NAME;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP COLUMN STRING_VAL;

ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01';
ALTER TABLE BATCH_STEP_EXECUTION MODIFY START_TIME DATETIME NULL;
