ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME DATETIME(6) NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE BATCH_STEP_EXECUTION MODIFY START_TIME DATETIME(6) NULL;

ALTER TABLE BATCH_JOB_SEQ
  DROP INDEX UNIQUE_KEY_UN, ADD PRIMARY KEY(UNIQUE_KEY);
ALTER TABLE BATCH_JOB_EXECUTION_SEQ
  DROP INDEX UNIQUE_KEY_UN, ADD PRIMARY KEY(UNIQUE_KEY);
ALTER TABLE BATCH_STEP_EXECUTION_SEQ
  DROP INDEX UNIQUE_KEY_UN, ADD PRIMARY KEY(UNIQUE_KEY);
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
  ADD PRIMARY KEY (JOB_EXECUTION_ID, KEY_NAME);
