CREATE PROCEDURE read_foos()
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
    DECLARE result CURSOR WITH RETURN FOR SELECT ID, NAME, VALUE FROM T_FOOS ORDER BY ID FOR READ ONLY;
    OPEN result;
END
/

CREATE PROCEDURE read_some_foos(IN from_id INTEGER, IN to_id INTEGER)
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
    DECLARE result CURSOR WITH RETURN FOR SELECT ID, NAME, VALUE FROM T_FOOS WHERE ID >= from_id and ID <= to_id ORDER BY ID FOR READ ONLY;
    OPEN result;
END
/
