ALTER TABLE BATCH_JOB_EXECUTION MODIFY CREATE_TIME DATETIME(6), MODIFY START_TIME DATETIME(6), MODIFY END_TIME DATETIME(6), MODIFY LAST_UPDATED DATETIME(6);
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY DATE_VAL DATETIME(6);
ALTER TABLE BATCH_STEP_EXECUTION MODIFY START_TIME DATETIME(6), MODIFY END_TIME DATETIME(6), MODIFY LAST_UPDATED DATETIME(6);