name: Create Release Notes
description: 'Create the release notes for a given milestone'
inputs:
  milestone:
    description: 'Name of the GitHub milestone for which release notes will be created'
    required: true
  token:
    description: 'Token to use for authentication with GitHub'
    required: true
runs:
  using: composite
  steps:
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: '25'
        distribution: 'temurin'
    - name: Generate release notes
      uses: spring-io/github-changelog-generator@c247eb874a8bbc2c7b91ed7227d8eb66eb639d38 # v0.0.13
      with:
        milestone: ${{ inputs.milestone }}
        token: ${{ inputs.token }}
    - name: Print release notes
      shell: bash
      run: cat changelog.md
