[[itemReader]]
= `ItemReader`

Although a simple concept, an `ItemReader` is the means for providing data from many
different types of input. The most general examples include:

* Flat File: Flat-file item readers read lines of data from a flat file that typically
describes records with fields of data defined by fixed positions in the file or delimited
by some special character (such as a comma).

* XML: XML `ItemReaders` process XML independently of technologies used for parsing,
mapping and validating objects. Input data allows for the validation of an XML file
against an XSD schema.

* Database: A database resource is accessed to return resultsets which can be mapped to
objects for processing. The default SQL `ItemReader` implementations invoke a `RowMapper`
to return objects, keep track of the current row if restart is required, store basic
statistics, and provide some transaction enhancements that are explained later.

There are many more possibilities, but we focus on the basic ones for this chapter. A
complete list of all available `ItemReader` implementations can be found in
xref:appendix.adoc#listOfReadersAndWriters[Appendix A].

`ItemReader` is a basic interface for generic
input operations, as shown in the following interface definition:

[source, java]
----
public interface ItemReader<T> {

    T read() throws Exception;

}
----

The `read` method defines the most essential contract of the `ItemReader`. Calling it
returns one item or `null` if no more items are left. An item might represent a line in a
file, a row in a database, or an element in an XML file. It is generally expected that
these are mapped to a usable domain object (such as `Trade`, `Foo`, or others), but there
is no requirement in the contract to do so.

It is expected that implementations of the `ItemReader` interface are forward only.
However, if the underlying resource is transactional (such as a JMS queue) then calling
`read` may return the same logical item on subsequent calls in a rollback scenario. It is
also worth noting that a lack of items to process by an `ItemReader` does not cause an
exception to be thrown. For example, a database `ItemReader` that is configured with a
query that returns 0 results returns `null` on the first invocation of `read`.

