-- Migration script for Spring Batch 6.0
-- Changes VARCHAR columns to NVARCHAR to align with Microsoft JDBC driver behavior
-- This improves performance by avoiding implicit conversions and reduces deadlock risk

-- BATCH_JOB_INSTANCE table
ALTER TABLE BATCH_JOB_INSTANCE ALTER COLUMN JOB_NAME NVARCHAR(100) NOT NULL;
ALTER TABLE BATCH_JOB_INSTANCE ALTER COLUMN JOB_KEY NVARCHAR(32) NOT NULL;

-- BATCH_JOB_EXECUTION table
ALTER TABLE BATCH_JOB_EXECUTION ALTER COLUMN STATUS NVARCHAR(10) NULL;
ALTER TABLE BATCH_JOB_EXECUTION ALTER COLUMN EXIT_CODE NVARCHAR(2500) NULL;
ALTER TABLE BATCH_JOB_EXECUTION ALTER COLUMN EXIT_MESSAGE NVARCHAR(2500) NULL;

-- BATCH_JOB_EXECUTION_PARAMS table
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_NAME NVARCHAR(100) NOT NULL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_TYPE NVARCHAR(100) NOT NULL;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN PARAMETER_VALUE NVARCHAR(2500);

-- BATCH_STEP_EXECUTION table
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN STEP_NAME NVARCHAR(100) NOT NULL;
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN STATUS NVARCHAR(10) NULL;
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN EXIT_CODE NVARCHAR(2500) NULL;
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN EXIT_MESSAGE NVARCHAR(2500) NULL;

-- BATCH_STEP_EXECUTION_CONTEXT table
ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ALTER COLUMN SHORT_CONTEXT NVARCHAR(2500) NOT NULL;
ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ALTER COLUMN SERIALIZED_CONTEXT NVARCHAR(MAX) NULL;

-- BATCH_JOB_EXECUTION_CONTEXT table
ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ALTER COLUMN SHORT_CONTEXT NVARCHAR(2500) NOT NULL;
ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ALTER COLUMN SERIALIZED_CONTEXT NVARCHAR(MAX) NULL;

-- Rename sequence BATCH_JOB_SEQ to BATCH_JOB_INSTANCE_SEQ
EXEC sp_rename 'BATCH_JOB_SEQ', 'BATCH_JOB_INSTANCE_SEQ';