-- MySQL: sequence emulated as a table
RENAME TABLE BATCH_JOB_SEQ TO BATCH_JOB_INSTANCE_SEQ;

-- Alternative (MySQL): create new table, migrate value, drop old
-- CREATE TABLE BATCH_JOB_INSTANCE_SEQ (ID BIGINT NOT NULL);
-- INSERT INTO BATCH_JOB_INSTANCE_SEQ (ID) SELECT ID FROM BATCH_JOB_SEQ;
-- DROP TABLE BATCH_JOB_SEQ;