name: Maven Central Extension Release

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: "Artifactory build name"
        required: true
      buildNumber:
        description: "Artifactory build number"
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set Up JFrog CLI
        uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Download Release Artifacts
        shell: bash
        run: jf rt download --spec .github/extension-release-files-spec.json --spec-vars 'buildname=${{ github.event.inputs.buildName }};buildnumber=${{ github.event.inputs.buildNumber }}'
      - name: Sync to Maven Central
        uses: spring-io/central-publish-action@5ea05c77127404d89c374ac4cd17b6ec6b0e7293 # v0.4.0
        with:
          token-name: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          token: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          timeout: 120m
